"""'change_photo'

Revision ID: 40efb24f43c9
Revises: efc1d752f44c
Create Date: 2020-04-06 19:39:54.820695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40efb24f43c9'
down_revision = 'efc1d752f44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo')
    # ### end Alembic commands ###
