"""empty message

Revision ID: efc1d752f44c
Revises: 9d8437cba99c
Create Date: 2020-04-03 18:22:52.697180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efc1d752f44c'
down_revision = '9d8437cba99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
